query NodeQuery($count: Int!, $offset: Int!) {
	nodes(first: $count, offset: $offset) {
		id
		platform
		host
		port
		maxSession
		hub
		capabilities {
			browserName
			maxInstances
			platform
			platformName
		}
	}
}
