query NodeQuery($id: String!) {
	node(id: $id) {
		id
		uri
		status
		maxSession
		capabilities {
			browserName
			marionette
			maxInstances
			platform
			platformName
			seleniumProtocol
			serverConfigUUID
		}
	}
}
